---
title: "MLB Summary"
date: 'Last updated: `r format(Sys.Date())`'
output:
  html_document:
    dpi: 500
    fig_width: 10
    fig_height: 7
---


```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```

## Stats & Standings {.tabset}

Below you'll find figures showing the current MLB standings and key advanced metrics I'm tracking for all 30 MLB teams.

```{r, echo =FALSE}

library(baseballr)
library(tidyverse)
library(teamcolors) # NFL team colors and logos
library(oddsapiR)
library(extrafont) # for extra fonts
# library(ggrepel) # better labels
library(ggimage)
library(glue)
library(ggtext)
library(reactable)
library(reactablefmtr)
library(gt)
library(gtExtras)
library(htmltools)
# library(webshot)
# library(ggalt) #for dumbbell plot
# library(ggforce)
# library(ggsci)

# Optional but makes R prefer not to display numbers in scientific notation
options(scipen = 9999)

# Create 538 GT table theme from Thomas Mock's blog.Comes from this post: https://themockup.blog/posts/2020-09-26-functions-and-themes-for-gt-tables/?panelset3=theme-code2&panelset4=theme-code3 
gt_nfl_theme_538 <- function(data,...) {
  data %>%
    # Add team logos w/ web_image
    text_transform(
      locations = cells_body(
        vars(team_logo_espn)
      ),
      fn = function(x) {
        web_image(
          url = x,
          height = 25
        )
      }
    ) %>%
    # Relabel columns
    cols_label(
      team_logo_espn = ""
    ) %>%
    opt_all_caps()  %>%
    opt_table_font(
      font = list(
        google_font("Chivo"),
        default_fonts()
      )
    ) %>%
    tab_style(
      style = cell_borders(
        sides = "bottom", color = "transparent", weight = px(2)
      ),
      locations = cells_body(
        columns = TRUE,
        # This is a relatively sneaky way of changing the bottom border
        # Regardless of data size
        rows = nrow(data$`_data`)
      )
    )  %>% 
    tab_options(
      column_labels.background.color = "white",
      table.border.top.width = px(3),
      table.border.top.color = "transparent",
      table.border.bottom.color = "transparent",
      table.border.bottom.width = px(3),
      column_labels.border.top.width = px(3),
      column_labels.border.top.color = "transparent",
      column_labels.border.bottom.width = px(3),
      column_labels.border.bottom.color = "black",
      data_row.padding = px(3),
      source_notes.font.size = 12,
      table.font.size = 16,
      heading.align = "left",
      ...
    ) 
}

# Define 538 table theme for Reactable table(s) below
theme_538 <- function() {
    reactable::reactableTheme(
        searchInputStyle = list(width = "31%", backgroundColor = "#F9F9F9"),
        style = list(
            fontFamily = "Chivo"
        ),
        headerStyle = list(
            "&:hover[aria-sort]" = list(
                background = "hsl(0, 0%, 80%)"),
            "&[aria-sort='ascending'], &[aria-sort='descending']" = list(
                background = "#555",
                color = "#FFF"
            ),
            borderColor = "#333"
        ),
        borderColor = "#CDCDCD"
    )
}


# Custom ggplot theme (inspired by Owen Phillips at the F5 substack blog)
theme_custom <- function () { 
  theme_minimal(base_size=11, base_family="Outfit") %+replace% 
    theme(
      panel.grid.minor = element_blank(),
      plot.background = element_rect(fill = 'floralwhite', color = "floralwhite")
    )
}


# define color palette to use in table
my_color_pal <- c("#ffffff", "#f2fbd2", "#c9ecb4", "#93d3ab", "#35b0ab")


# load teamcolors and logos
mlb_teamcolors <- read_csv('mlb_teamcolors.csv') %>% 
    mutate(team_abbr = case_when(team_abbr == "OAK" ~ "ATH",
                     TRUE ~ team_abbr)
           )


```


***
### Overall Standings

```{r Standings}

today <- Sys.Date()
#today <- as.character(today)


al_standings <- bref_standings_on_date(today, "AL Overall", from = FALSE)
nl_standings <- bref_standings_on_date(today, "NL Overall", from = FALSE)

mlb_standings <- rbind(al_standings, nl_standings)

mlb_standings <- mlb_standings %>%
    arrange(desc(`W-L%`))

# join in team logos and colors
mlb_standings <- mlb_standings %>%
    left_join(mlb_teamcolors %>% 
                  select(name, team_abbr, division, primary, team_logo_espn), by = c("Tm" = "team_abbr"))

# make reactable standings table  
mlb_standings <- mlb_standings %>%
    mutate(Rank = row_number()) %>%
    select(Rank, team_logo_espn, name, division, W:`pythW-L%`) %>%
    mutate(run_diff = RS-RA,
           proj_w = round(162*`pythW-L%`),
           proj_l = round(162-proj_w)) %>%
    select(Rank:GB,`pythW-L%`:proj_l)

standings_table <- reactable(
  mlb_standings,
  theme = theme_538,
                  showSortIcon = TRUE,
                  searchable = TRUE,
                  language = reactableLang(
                      searchPlaceholder = "SEARCH FOR A TEAM..."),
                  defaultPageSize = 100,
                  columns = list(
                      name = colDef(name = "Team",
                                    minWidth = 160,
                                       align = "left"),
                      run_diff = colDef(name = "Run Diff"),
                      division = colDef(name = "Division", 
                                        minWidth = 100),
                      proj_w = colDef(name = "Proj. W"),
                      proj_l = colDef(name = "Proj. L"),
                      team_logo_espn = colDef(
                          name = "",
                          maxWidth = 70,
                          align = "center",
                          cell = embed_img(height = "25", width = "30")
                      )),
                  pagination = FALSE,
                  compact = TRUE, 
                  borderless = FALSE, 
                  striped = FALSE,
                  fullWidth = FALSE, 
                  defaultColDef = colDef(align = "center", minWidth = 75)
  ) 

standings_table


```


### Division Standings

``` {r Division Standings, echo = FALSE}

prior_day <- Sys.Date() - 1

# Reusable helper functions to get division standings from baseballr
get_division_standings <- function(division_name) {
  bref_standings_on_date(prior_day, division_name, from = FALSE) %>%
    left_join(mlb_teamcolors %>% select(team_abbr, team_logo_espn), by = c("Tm" = "team_abbr")) %>%
    select(team_logo_espn, Tm, W:`pythW-L%`)
}

make_standings_table <- function(df, division_name) {
  df %>%
    gt() %>%
    cols_label(team_logo_espn = "") %>%
    gt_img_rows(columns = team_logo_espn, img_source = "web", height = 30) %>%
    tab_header(title = md(glue::glue("**{division_name}**")),
               subtitle = glue::glue("Data thru games as of {prior_day}.")) %>%
    tab_source_note(source_note = md("DATA: baseballR (Bill Petti)<br>TABLE: @steodosescu")) %>%
    tab_options(
      column_labels.background.color = "white",
      table.border.top.width = px(3),
      table.border.top.color = "white",
      table.border.bottom.color = "white",
      table.border.bottom.width = px(3),
      column_labels.border.top.width = px(3),
      column_labels.border.top.color = "white",
      column_labels.border.bottom.width = px(3),
      column_labels.border.bottom.color = "black",
      data_row.padding = px(3),
      source_notes.font.size = 12,
      table.font.size = 16,
      heading.align = "center"
    ) %>%
    tab_style(
      style = cell_text(weight = "bold"),
      locations = cells_column_labels(everything())
    )
}

# generate all division tables
nl_west <- make_standings_table(get_division_standings("NL West"), "NL West")
al_west <- make_standings_table(get_division_standings("AL West"), "AL West")

# nl_central <- make_standings_table(get_division_standings("NL Central"), "NL Central")
# al_central <- make_standings_table(get_division_standings("AL Central"), "AL Central")
# 
# nl_east <- make_standings_table(get_division_standings("NL East"), "NL East")
# al_east <- make_standings_table(get_division_standings("AL East"), "AL East")


```


```{r West, echo = FALSE}

gt_two_column_layout(
  list(nl_west, al_west),
  output = "html",
  vwidth = 725,
  vheight = 475
)

```

```{r Central, echo = FALSE}

# gt_two_column_layout(
#   list(nl_central, al_central),
#   output = "html",
#   vwidth = 725,
#   vheight = 475
# )
# 
# ```
# 
# ```{r East, echo = FALSE}
# 
# gt_two_column_layout(
#   list(nl_east, al_east),
#   output = "html",
#   vwidth = 725,
#   vheight = 475
# )

```

### World Series Odds

```{=html}
<iframe title="2025 World Series Odds" aria-label="Table" id="datawrapper-chart-jiWGu" src="https://datawrapper.dwcdn.net/jiWGu/1/" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="1803" data-external="1"></iframe><script type="text/javascript">!function(){"use strict";window.addEventListener("message",function(a){if(void 0!==a.data["datawrapper-height"]){var e=document.querySelectorAll("iframe");for(var t in a.data["datawrapper-height"])for(var r,i=0;r=e[i];i++)if(r.contentWindow===a.source){var d=a.data["datawrapper-height"][t]+"px";r.style.height=d}}})}();
</script>

```




