---
title: "MLB Summary"
date: 'Last updated: `r format(Sys.Date())`'
format:
  html:
    theme: cosmo
    dpi: 500
    fig_width: 10
    fig_height: 7
---


```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```

Below you'll find figures showing the current MLB standings and key advanced metrics I'm tracking for all 30 MLB teams.

```{r, echo =FALSE}

library(baseballr)
library(tidyverse)
library(teamcolors) # NFL team colors and logos
library(extrafont) # for extra fonts
library(ggrepel) # better labels
library(ggimage)
library(glue)
library(ggtext)
library(reactable)
library(reactablefmtr)
library(gt)
library(gtExtras)
library(webshot)
library(ggalt) #for dumbbell plot
library(ggforce)
library(ggsci)

# Optional but makes R prefer not to display numbers in scientific notation
options(scipen = 9999)

# Create 538 GT table theme from Thomas Mock's blog.Comes from this post: https://themockup.blog/posts/2020-09-26-functions-and-themes-for-gt-tables/?panelset3=theme-code2&panelset4=theme-code3 
gt_nfl_theme_538 <- function(data,...) {
  data %>%
    # Add team logos w/ web_image
    text_transform(
      locations = cells_body(
        vars(team_logo_espn)
      ),
      fn = function(x) {
        web_image(
          url = x,
          height = 25
        )
      }
    ) %>%
    # Relabel columns
    cols_label(
      team_logo_espn = ""
    ) %>%
    opt_all_caps()  %>%
    opt_table_font(
      font = list(
        google_font("Chivo"),
        default_fonts()
      )
    ) %>%
    tab_style(
      style = cell_borders(
        sides = "bottom", color = "transparent", weight = px(2)
      ),
      locations = cells_body(
        columns = TRUE,
        # This is a relatively sneaky way of changing the bottom border
        # Regardless of data size
        rows = nrow(data$`_data`)
      )
    )  %>% 
    tab_options(
      column_labels.background.color = "white",
      table.border.top.width = px(3),
      table.border.top.color = "transparent",
      table.border.bottom.color = "transparent",
      table.border.bottom.width = px(3),
      column_labels.border.top.width = px(3),
      column_labels.border.top.color = "transparent",
      column_labels.border.bottom.width = px(3),
      column_labels.border.bottom.color = "black",
      data_row.padding = px(3),
      source_notes.font.size = 12,
      table.font.size = 16,
      heading.align = "left",
      ...
    ) 
}

# Define 538 table theme for Reactable table(s) below
theme_538 <- function() {
    reactable::reactableTheme(
        searchInputStyle = list(width = "31%", backgroundColor = "#F9F9F9"),
        style = list(
            fontFamily = "Chivo"
        ),
        headerStyle = list(
            "&:hover[aria-sort]" = list(
                background = "hsl(0, 0%, 80%)"),
            "&[aria-sort='ascending'], &[aria-sort='descending']" = list(
                background = "#555",
                color = "#FFF"
            ),
            borderColor = "#333"
        ),
        borderColor = "#CDCDCD"
    )
}


# Custom ggplot theme (inspired by Owen Phillips at the F5 substack blog)
theme_custom <- function () { 
  theme_minimal(base_size=11, base_family="Outfit") %+replace% 
    theme(
      panel.grid.minor = element_blank(),
      plot.background = element_rect(fill = 'floralwhite', color = "floralwhite")
    )
}


#Define color palette to use in table
my_color_pal <- c("#ffffff", "#f2fbd2", "#c9ecb4", "#93d3ab", "#35b0ab")

```


***
### Current Standings

```{r}

today <- Sys.Date()
#today <- as.character(today)


al_standings <- bref_standings_on_date(today, "AL Overall", from = FALSE)
nl_standings <- bref_standings_on_date(today, "NL Overall", from = FALSE)

mlb_standings <- rbind(al_standings, nl_standings)

mlb_standings <- mlb_standings %>%
    arrange(desc(`W-L%`))

# load teamcolors and logos
mlb_teamcolors <- read_csv('mlb_teamcolors.csv')

# join in team logos and colors
mlb_standings <- mlb_standings %>%
    left_join(mlb_teamcolors %>% select(name, team_abbr, primary, logo), by = c("Tm" = "team_abbr"))

# make reactable standings table  
mlb_standings <- mlb_standings %>%
    mutate(Rank = row_number()) %>%
    select(Rank, logo, name, W:`pythW-L%`)

standings_table <- reactable(
  mlb_standings,
  theme = theme_538,
                  showSortIcon = TRUE,
                  searchable = TRUE,
                  language = reactableLang(
                      searchPlaceholder = "SEARCH FOR A TEAM..."),
                  defaultPageSize = 100,
                  columns = list(
                      name = colDef(name = "Team",
                                       align = "left"),
                      # `Overall EPA` = colDef(name = "Overall EPA/Play",
                      #                  align = "right",
                      #                  style = color_scales(off_def_epa2, colors = my_color_pal),
                      #                  format =  colFormat(digits = 2)),
                      # off_epa = colDef(name = "Off EPA/Play",
                      #                  align = "right",
                      #                  format =  colFormat(digits = 2)),
                      # def_epa = colDef(name = "Def EPA/Play",
                      #                  align = "right",
                      #                  format =  colFormat(digits = 2)),
                      # epa_per_pass = colDef(name = "EPA/Pass",
                      #                  align = "right",
                      #                  format =  colFormat(digits = 2)),
                      # epa_per_rush = colDef(name = "EPA/Rush",
                      #                  align = "right",
                      #                  format =  colFormat(digits = 2)),
                      # def_epa_per_pass = colDef(name = "Def EPA/Pass",
                      #                  align = "right",
                      #                  format =  colFormat(digits = 2)),
                      # def_epa_per_rush = colDef(name = "Def EPA/Rush",
                      #                  align = "right",
                      #                  format =  colFormat(digits = 2)),
                      # success_per_pass = colDef(name = "Pass SR",
                      #                  align = "right",
                      #                  format =  colFormat(percent = TRUE, digits = 1)),
                      #  success_per_rush = colDef(name = "Rush SR",
                      #                  align = "right",
                      #                  format =  colFormat(percent = TRUE, digits = 1)),
                      # 
                      ### add logos using embed_img()
                      logo = colDef(
                          name = "",
                          maxWidth = 70,
                          align = "center",
                          cell = embed_img(height = "25", width = "30")
                      )),
                  pagination = FALSE,
                  compact = TRUE, 
                  borderless = FALSE, 
                  striped = FALSE,
                  fullWidth = FALSE, 
                  defaultColDef = colDef(align = "center", minWidth = 95)
  ) 

standings_table

```

