---
title: "Players"
date: 'Last updated: `r format(Sys.Date())`'
output:
  html_document:
    dpi: 500
    fig_width: 10
    fig_height: 7
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

Below you'll find figures showing the latest traditional and advanced metrics I'm tracking for all 30 MLB teams.

```{r, echo = FALSE}

library(baseballr)
library(tidyverse)
library(teamcolors) # team colors and logos
library(extrafont) # for extra fonts
library(ggrepel) # better labels
library(ggimage)
library(glue)
library(ggtext)
library(ggforce)
library(ggsci)
library(paletteer)
library(prismatic)
library(gt)
library(gtExtras)

# Optional but makes R prefer not to display numbers in scientific notation
options(scipen = 9999)

# Custom ggplot theme (inspired by Owen Phillips at the F5 substack blog)
theme_custom <- function () { 
  theme_minimal(base_size=11, base_family="Chivo") %+replace% 
    theme(
      panel.grid.minor = element_blank(),
      plot.background = element_rect(fill = 'floralwhite', color = "floralwhite"),
      plot.subtitle = element_text(color = "grey60")
    )
}

# Define an aspect ratio to use throughout. This value is the golden ratio which provides a wider than tall rectangle
asp_ratio <- 1.618 

# load teamcolors and logos
mlb_teamcolors <- read_csv('mlb_teamcolors.csv') %>% 
    mutate(team_abbr = case_when(team_abbr == "OAK" ~ "ATH", # A's are no longer called OAK
                     TRUE ~ team_abbr,)
           )

# today's date for graphics
today <- Sys.Date()-1

# load Fangraohs pitching and batting leaders data
fg_pitcher_leaders <- baseballr::fg_pitcher_leaders(startseason = 2025, endseason = 2025)
fg_batter_leaders <- baseballr::fg_batter_leaders(startseason = 2025, endseason = 2025)

```


## MLB Leaders {.tabset}

### Pitching

The below shows MLB pitching and hitting leaders. Data sourced from Fangraphs. 

```{r Pitch Leaders, echo = FALSE}

## 1. ---------- Pitching Leaders Table ----------------------

top_pitchers <- fg_pitcher_leaders %>% 
    select(team_name, PlayerName, IP, W, L, ERA, WHIP, BABIP, K_BB, WAR) %>% 
    slice_head(n = 20) %>% 
    left_join(mlb_teamcolors %>% 
                  select(name, team_abbr, division, primary, team_logo_espn), by = c("team_name" = "team_abbr"))
    

# gt table
top_pitchers %>% 
    mutate(rank = row_number()) %>% 
    select(rank, team_logo_espn, team_name:WAR) %>% 
    gt() %>% 
    cols_label(rank = "",
               team_logo_espn = "",
               team_name = "Team",
               PlayerName = "Player",
               K_BB = "K/BB"
               ) %>% 
    gt_img_rows(columns = team_logo_espn, img_source = "web", height = 30) %>%
    fmt_number(columns = c(ERA, WHIP, BABIP), decimals = 3) %>%
    fmt_number(columns = c(K_BB, WAR), decimals = 1) %>%
  cols_align(align = "left",
             columns = 1) %>%
  tab_header(title = md("**MLB Pitching Leaders**"),
             subtitle = glue("Top 20 pitchers, according to Fangraphs, sorted by overall WAR. Data last updated thru {today}.")) %>%
  tab_source_note(
    source_note = md("DATA: baseballR (Bill Petti)<br>TABLE: @steodosescu")) %>% 
    tab_options(
        column_labels.background.color = "white",
        table.border.top.width = px(3),
        table.border.top.color = "white",
        table.border.bottom.color = "white",
        table.border.bottom.width = px(3),
        column_labels.border.top.width = px(3),
        column_labels.border.top.color = "white",
        column_labels.border.bottom.width = px(3),
        column_labels.border.bottom.color = "black",
        data_row.padding = px(3),
        source_notes.font.size = 12,
        table.font.size = 16,
        heading.align = "center"
    ) %>% 
    tab_style(
        style = cell_text(weight = "bold"),
        locations = cells_column_labels(everything())
        ) 

```


### Batting

```{r Batting Leaders, echo = FALSE}

## 2. ---------- Batting Leaders Table ----------------------

top_batters <- fg_batter_leaders %>% 
    select(team_name, PlayerName, AVG, OPS, wOBA, R, RBI, HR, WAR) %>% 
    slice_head(n = 20) %>% 
    left_join(mlb_teamcolors %>% 
                  select(name, team_abbr, division, primary, team_logo_espn), by = c("team_name" = "team_abbr"))


# gt table
top_batters %>% 
    mutate(rank = row_number()) %>% 
    select(rank, team_logo_espn, team_name:WAR) %>% 
    gt() %>% 
    cols_label(rank = "",
               team_logo_espn = "",
               team_name = "Team",
               PlayerName = "Player"
               ) %>% 
    gt_img_rows(columns = team_logo_espn, img_source = "web", height = 30) %>%
    fmt_number(columns = c(AVG, OPS, wOBA), decimals = 3) %>% 
    fmt_number(columns = WAR, decimals = 1) %>% 
  cols_align(align = "left",
             columns = 1) %>%
  tab_header(title = md("**MLB Batting Leaders**"),
             subtitle = glue("Top 20 batters, according to Fangraphs, sorted by overall WAR. Data last updated thru {today}.")) %>%
  tab_source_note(
    source_note = md("DATA: baseballR (Bill Petti)<br>TABLE: @steodosescu")) %>% 
    tab_options(
        column_labels.background.color = "white",
        table.border.top.width = px(3),
        table.border.top.color = "white",
        table.border.bottom.color = "white",
        table.border.bottom.width = px(3),
        column_labels.border.top.width = px(3),
        column_labels.border.top.color = "white",
        column_labels.border.bottom.width = px(3),
        column_labels.border.bottom.color = "black",
        data_row.padding = px(3),
        source_notes.font.size = 12,
        table.font.size = 16,
        heading.align = "center"
    ) %>% 
    tab_style(
        style = cell_text(weight = "bold"),
        locations = cells_column_labels(everything())
        )
    


```

