---
title: "Teams"
format:
  html:
    theme: cosmo
    dpi: 500
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```

Below you'll find figures showing the current MLB standings and key advanced metrics I'm tracking for all 30 MLB teams.

```{r, echo =FALSE}

library(baseballr)
library(tidyverse)
library(teamcolors) # team colors and logos
library(extrafont) # for extra fonts
library(ggrepel) # better labels
library(ggimage)
library(glue)
library(ggtext)
library(reactable)
library(reactablefmtr)
library(gt)
library(gtExtras)
library(webshot)
library(ggalt) #for dumbbell plot
library(ggforce)
library(ggsci)

# Optional but makes R prefer not to display numbers in scientific notation
options(scipen = 9999)

# Custom ggplot theme (inspired by Owen Phillips at the F5 substack blog)
theme_custom <- function () { 
  theme_minimal(base_size=11, base_family="Chivo") %+replace% 
    theme(
      panel.grid.minor = element_blank(),
      plot.background = element_rect(fill = 'floralwhite', color = "floralwhite")
    )
}

# Define an aspect ratio to use throughout. This value is the golden ratio which provides a wider than tall rectangle
asp_ratio <- 1.618 


## 1. ---------- Pythagorean Win % Plot ----------------------

today <- Sys.Date()
al_standings <- bref_standings_on_date(today, "AL Overall", from = FALSE)
nl_standings <- bref_standings_on_date(today, "NL Overall", from = FALSE)

mlb_standings <- rbind(al_standings, nl_standings)

mlb_standings <- mlb_standings %>%
    arrange(desc(`W-L%`))

# load teamcolors and logos
mlb_teamcolors <- read_csv('mlb_teamcolors.csv')

# join in team logos and colors
mlb_standings <- mlb_standings %>%
    left_join(mlb_teamcolors %>% 
                  select(name, team_abbr, division, primary, logo), by = c("Tm" = "team_abbr"))

# clean up df  
mlb_standings <- mlb_standings %>%
    mutate(Rank = row_number()) %>%
    select(Rank, logo, name, division, W:`pythW-L%`)


# make visual
mlb_standings %>% 
    ggplot(aes(x = `W-L%`, y = `pythW-L%`)) + 
    geom_image(aes(image = logo), size = 0.065, by = "width", asp = asp_ratio) +
    annotate("text", x=0.35, y=0.55, label = "Better than Actual Record", color = "#00BA38", family = 'Outfit') +
    annotate("text", x=0.55, y=0.35, label = "Worse than Actual Record", color = "#F8766D", family = 'Outfit') +
    theme_custom() +
    #geom_abline(slope = 1, alpha = .2) +
    geom_smooth(method = "lm", se = FALSE, color="gray", alpha = 0.2) +
    scale_y_continuous(labels = scales::percent_format()) +
    scale_x_continuous(labels = scales::percent_format()) +
    theme_custom() +
    labs(title = 'Pythagorean Wins',
         x = "Actual Win %",
         y = "Pythagorean Win %",
         subtitle = "Pythagorean Win % helps evaluate how teams perform vs expectations. Thru **{today}.**",
         caption = "Data: baseballR (Bill Petti) | Plot: @steodosescu") +
  theme(plot.title.position = "plot",
        plot.title = element_text(face = "bold", 
                                  size = 20, 
                                  hjust = 0.5
    ),
    plot.subtitle = element_text(
      size = 10,
      hjust = 0.5)
  ) +
  theme(plot.subtitle = element_markdown()) 
    

```



```{r, echo =FALSE}

## 2. ---------- Run Differential Evolution Plot ----------------------

# load MLB schedule
games <- mlb_schedule(season = "2024") %>%
    filter(game_type == 'R')


```
